name = "LogSpline"
uuid = "6b40cf57-2cb8-450d-abd9-e1a605a46c2e"
authors = ["Francesco Alemanno <francescoalemanno710@gmail.com>"]
version = "1.0.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "^1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Test", "Random"]
